package com.pravera.geofence_service.errors

enum class ErrorCodes {
	ACTIVITY_NOT_REGISTERED,
	PERMISSION_REQUEST_CANCELLED,
	ACTIVITY_UPDATES_REQUEST_FAILED,
	ACTIVITY_UPDATES_REMOVE_FAILED,
	ACTIVITY_DATA_ENCODING_FAILED
}
